apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-platform

resources:
  - namespace.yml
  - postgres
  - redis
  - gateway
  - product
  - order

labels:
  - pairs:
      app.kubernetes.io/part-of: ecommerce-platform
    includeSelectors: false
    includeTemplates: true

patches:
  - path: deployment-defaults.yml
    target:
      kind: Deployment