spring:
  application:
    name: discovery

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info, metrics

logging:
  level:
    root: INFO
    com.aziz.discovery: DEBUG
  pattern:
    console: "%d{HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

server:
  port: ${APP_PORT:8080}