spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 2000ms
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**

            - id: cart-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/carts/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**

            - id: order-items-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/order-items/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://discovery:8080/eureka/

jwt:
  secret: ${JWT_SECRET}
  access-token:
    secured: false
  refresh-token:
    secured: false

session:
  secure: false