spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: aziz
    password: aziz333
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      server:
        webmvc:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**

            - id: cart-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/carts/**

            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**

            - id: order-items-service
              uri: lb://order-service
              predicates:
                - Path=/api/v1/order-items/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

jwt:
  secret: ${JWT_SECRET:local-dev-only-secret-change-me-0123456789}
  access-token:
    secured: false
  refresh-token:
    secured: false

session:
  secure: false