apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

configMapGenerator:
  - name: order-config
    envs: [config.env]

secretGenerator:
  - name: order-secret
    envs: [secret.enc.env]

labels:
  - pairs:
      app: order
      app.kubernetes.io/name: order
    includeSelectors: false
    includeTemplates: true