apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP